language: node_js
    - "7"

# All of these are fake.
env:
    - TOTAL_PBKDF2_ITERATIONS=3472
    - PBKDF2_KEY_LENGTH=128
    - PBKDF2_HMAC=sha256
    - SALT_LENGTH=16
    - PEPPER_KEY="ILikeBreadAndButter"
    - RECAPTCHA_SECRET="ILikeToastAndJam"
    - POSTMARK_KEY="HeLikesBreadAndButter"
    - COOKIE_SECRET="HeLikesToastAndJam"

# Run MongoDB
services:
    - mongodb

before_script:
    - npm install

# Run the tests
script: 
    - karma start