sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
    - "7"

# Run MongoDB
services:
    - mongodb

before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - npm install

# Run the tests
script:
    - ./node_modules/.bin/karma start --single-run
    - ./node_modules/.bin/tsc
    - ./build.sh
    - node ./dist/main.js